name: Create Release

on: 
  push:
    branches: ["main"]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout GCM
      uses: actions/checkout@v3
      with:
        repository: HHS/ASPR-8
        path: gcm

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Get Version
      run: |
        echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml)" >> "$GITHUB_ENV"
        cd gcm
        git checkout dev
        git checkout -b update-util-version
        cd gcm
        sed -i "0,/<util.version>.*<\/util.version>/s//<util.version>${VERSION}<\/util.version>/g" pom.xml
        git add pom.xml
        git commit -m "update util version"
        gh pr create --head --fill
        gh pr merge --auto

      